// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoList.Repository;

namespace TodoList.Repository.Migrations
{
    [DbContext(typeof(TodoListDbContext))]
    partial class TodoListDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TodoList.Repository.Entity.BookEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<decimal>("Price");

                    b.Property<DateTime>("PublishDate");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("book_luoziqiong");
                });

            modelBuilder.Entity("TodoList.Repository.Entity.State", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DbCreateDate")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DbUpdateDate")
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("state")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.ToTable("lzq_state");
                });

            modelBuilder.Entity("TodoList.Repository.Entity.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("DbCreateDate")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DbUpdateDate")
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<DateTime>("FinishDate")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Priority");

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("StateId");

                    b.Property<long>("UserId");

                    b.HasKey("Id");

                    b.ToTable("lzq_todolist");
                });

            modelBuilder.Entity("TodoList.Repository.Entity.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DbCreateDate")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DbUpdateDate")
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.HasKey("Id");

                    b.ToTable("lzq_user");
                });
#pragma warning restore 612, 618
        }
    }
}
